services:
  ftp:
    build: ./resources
    ports:
      - "2220:20"
      - "2221:21"
      - "2222:22"
      - "10000-10010:10000-10010"
    volumes:
      - ./resources/ftp_files:/home/test_user
      - ./:/other