services:
  ftp:
    build: ./
    ports:
      - "2220:20"
      - "2221:21"
      - "2222:22"
      - "10000-10010:10000-10010"
    volumes:
      # C:\Users\jacob\Dev\ortussollutions\bx-ftp\resources\ftp_files:/home/test_user
      - ./ftp_files:/home/test_user

    # docker run --rm -it -p 2220:20 -p 2221:21 -p 2222:22 -p 10000-10010:10000-10010 -v C:\Users\jacob\Dev\ortussollutions\bx-ftp\resources\ftp_files:/home/test_user xftp